default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: critical
      threads: 5
      processes: 5
      polling_interval: 0.1

    - queues: high
      threads: 4
      processes: 3
      polling_interval: 0.1

    - queues: default
      threads: 2
      processes: 2
      polling_interval: 0.1

    - queues: low
      threads: 2
      processes: 1
      polling_interval: 0.1

    - queues: bulk
      threads: 1
      processes: 1
      polling_interval: 0.1

development:
  <<: *default

test:
  <<: *default

production:
