periodic_cleanup:
  class: CleanUpJob
  queue: low
  args: [ 1, { batch_size: 3 } ]
  schedule: every minute
clear_solid_queue_finished_jobs:
  command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
  schedule: every hour at minute 12
